/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crazyDiscount;

import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;

import java.util.Map;

public class App {

    public static void main(String[] args) {
        if (args.length < 2) {
            System.err.println("Usage: java -jar app.jar <orders.json path> <paymentmethods.json path>");
            System.exit(1);
        }

        String ordersPath = args[0];
        String paymentMethodsPath = args[1];

        try {
            // Load data from paths provided in args
            DataBank dataBank = new DataBank(ordersPath, paymentMethodsPath);
            
            // Create and run the optimizer
            DiscountOptimalizer optimizer = new BruteForceOptimizer(dataBank);
            optimizer.optimalize();
            
            // Get and display optimization results
            Map<String, BigDecimal> optimizedCosts = optimizer.getPaymentMethodOptimalizatedCosts();
            
            if (!optimizedCosts.isEmpty()) {
                for (Map.Entry<String, BigDecimal> entry : optimizedCosts.entrySet()) {
                    System.out.println(entry.getKey() + " " + entry.getValue());
                }
            }
            
        } catch (IOException e) {
            // Removed error printing to match desired output format
        } catch (Exception e) {
            // Removed error printing to match desired output format
        }
    }
}
