/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crazyDiscount;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length < 2) {
            System.out.println("Usage: java -jar app.jar <orders_json_path> <payment_methods_json_path>");
            return;
        }
        
        String ordersPath = args[0];
        String paymentMethodsPath = args[1];
        
        try {
            OrdersBank ordersBank = new OrdersBank(ordersPath);
            PaymentsMethodsBank paymentsMethodsBank = new PaymentsMethodsBank(paymentMethodsPath);
            
            System.out.println("Successfully loaded orders and payment methods!");
            System.out.println("Orders data: " + ordersBank.getOrders());
            System.out.println("Payment methods data: " + paymentsMethodsBank.getPaymentMethods());
        } catch (IOException e) {
            System.err.println("Error loading JSON files: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
